sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
    - libglpk-dev

before_install:
  - pip install --ignore-installed --upgrade pip setuptools wheel
  - pip install -U --only-binary=numpy,scipy numpy scipy
  - pip install matplotlib
  - pip install nose

install:
  - python setup.py sdist
  - pip install dist/polytope-*.tar.gz

script:
  # w/o `cvxopt`
  - ./run_tests.py --outofsource
  # with `cvxopt`
  - curl -sO http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.4.tar.gz
    && echo '698b5c455645bb1ad29a185f0d52025f3bd7cb7261e182c8878b0eb60567a714  SuiteSparse-4.5.4.tar.gz'
    | shasum -a 256 -c -
  - tar -xzf SuiteSparse-4.5.4.tar.gz
  - export CVXOPT_SUITESPARSE_SRC_DIR=`pwd`/SuiteSparse
  - export CVXOPT_BUILD_GLPK=1
  - pip install cvxopt
  - python -c "import cvxopt.glpk"
  - ./run_tests.py --outofsource

notifications:
  email: false
